Add TCP/UDP routes and access control to spec
servicemeshinterface/smi-spec pull request #185
Opened 2020-08-13 07:52 UTC by stefanprodan

Changes:

* Add `matches.ports` field to TCPRoute spec
* Add UDPRoute spec
* Replace TrafficTarget `destination.port` with TCP/UDPRoute `matches.ports` (**breaking change**)

These changes make the TrafficTarget less verbose when a service exposes multiple ports, a single TrafficTarget can match multiple protocols and ports. TrafficTarget was extended in order to support UDP traffic.

Ref: #108 #156 #150 #151

2020-09-16 16:06 UTC, michelleN approved these changes

2020-09-16 17:12 UTC, michelleN requested changes

2020-09-16 17:12 UTC, michelleN commented on apis/traffic-access/traffic-access-WD.md
> +**Compatible With:** specs.smi-spec.io/v1alpha4
I think this should be specs.smi-spec.io/v1alpha4-WD

2020-09-29 21:18 UTC, patricekrakow commented
Following the discussion at #188, could we consider having a `TrafficTarget` without the `rules` field?
@stefanprodan you wrote:

> The `matches.ports` is an optional element, if not specified, traffic will be allowed to all ports on the destination service.

So, if I want to allow TCP traffic for all ports, I have to create a `TCPRoute` containing no information. Is it not then better to allow the developer to omit the `rules`, compared to asking to add a rule with no constraint?

2020-09-30 17:30 UTC, michelleN approved these changes

2020-10-01 17:50 UTC, leecalcote approved these changes

2020-10-01 17:50 UTC, leecalcote commented on apis/traffic-specs/traffic-specs-WD.md
> +    ports: []
Looking good. 👍

2020-10-01 17:50 UTC, leecalcote commented on apis/traffic-access/traffic-access-WD.md
> +**Compatible With:** specs.smi-spec.io/v1alpha4
```suggestion
**Compatible With:** specs.smi-spec.io/v1alpha4-WD
```

2020-10-14 17:11 UTC, merged